eureka:
  client:
    register-with-eureka: true
    fetch-registry: true 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    server:
       waitTimeInMsWhenSyncEmpty: 0  
  instance:
    hostname: localhost    
server:
  port: 8082
spring:
  application:
    name: PAYMENT-EUREKA-SERVER    